name: tearrform deployment 

on: workflow_dispatch
  # push: 
  #   branches:
  #     - main

jobs:
  my_first_job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/copy files init agent
        uses: actions/checkout@v7.0.0

      - name: HashiCorp - Setup Terraform/install
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Azure Login
        uses: Azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
       
      - name: Terraform Init
        working-directory: ./parent module
        run: terraform init

      - name: Terraform Plan
        working-directory: ./parent module
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply
      
      
        
    
  
  
