name: tearrform deployment 

on: 
  push: 
    branches:
      - main

jobs:
  my_first_job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/copy files init agent
        uses: actions/checkout@v7.0.0

      - name: HashiCorp - Setup Terraform/install
        uses: hashicorp/setup-terraform@v2.0.3
       
      - name: Terraform Init
        run: terraform init

      
      
        
    
  
  
